name: ohanas_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  http: ^1.2.2
  cached_network_image: ^3.3.1
  socket_io_client: ^2.0.3+1
  intl: ^0.18.0
  flutter_stripe: ^11.1.0  # ← NUEVA LÍNEA AGREGADA

  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo3.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true

  assets:
    - assets/icons/like.png
    - assets/icons/like2.png
    - assets/icons/like7.png
    - assets/icons/adopcion.png
    - assets/icons/adopcion2.png
    - assets/icons/adopcion3.png
    - assets/icons/apoyar.png
    - assets/icons/apoyar2.png
    - assets/icons/escribiendo.png
    - assets/icons/compartir.png
    - assets/icons/compartir2.png
    - assets/icons/mapache.jpg

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700